### ISSUE TITLE
README should mention how to "vagrant box update" 

### ISSUE THREAD

**Issue by knbknb** [felipecrs/dev-ubuntu#26]
Hi Felipe ,

it's me again. I still use your vagrant dev-box as a base for one of my  projects. I noticed that you are updating this setup script quite  frequently. from v1 to v4 in one month. Nice! 

As a sideeffect I get these messages: 

```
vagrant box outdated
Checking if box 'felipecassiors/ubuntu1804-4dev' version '3.0.0' is up to date...
A newer version of the box 'felipecassiors/ubuntu1804-4dev' for provider 'virtualbox' is
available! You currently have version '3.0.0'. The latest is version
'4.0.1'. Run `vagrant box update` to update.
```

However you should also explain how to do this, how to *update* the vagrant box.
Perhaps mention this generally in a brief paragraph in the README .

Meanwhile I have figured out for myself how the `vagrant destroy` -> `vagrant box update` -> `vagrant up` sequence works. I don't need any help with this. 
But I think that others will not know this immediately, how to upgrade.  (Admittedly I also tend to forget the exact steps after 2 weeks or so... )

(And I personally have the luxury that I can delete all VirtualBox instances based on older releases of  box ''felipecassiors/ubuntu1804-4dev' immediately. Nobody is affected besides me. But maybe others cannot delete and rebuild their Vbox instnaces immediately. Just saying that upgrade has some implications)

Thanks again,

Knut

PS thisissue could be labeled "enhancement" or "documentation".

**Comment by felipecrs** [comment]
Hi, glad to see you again!

Yeah, newer versions of the box have some exciting news: the new Flat Remix theme and the ability to start the box without having to manually edit the `Vagrantfile` (I'll add a new section on the documentation about this later, it will be called **Quickstart**).

Great, I'll update the documentation with instructions on how to update the box and its side effects.

**Comment by knbknb** [comment]
Cool, I like the new theme!  Will continue to work with it.

First impression that black-blue-pink background screen and lock screen creates : OK. Maybe I'll replace it with something from the natural world (animal like the ubuntu beaver fits  better my personal intended use)

Dock Bar now at the bottom of the screen (instead of on the left) is nice to have, too.

**Comment by felipecrs** [comment]
@knbknb I'm also not sure about the wallpaper. I just chose the best rated one on [wallhaven.cc](https://wallhaven.cc/search?categories=100&purity=100&topRange=1y&sorting=toplist&order=desc&page=2).

The problem with the default Ubuntu wallpaper is that the colors of it don't contrast well with the Flat Remix theme.

**Comment by knbknb** [comment]
Aha. I need a woodpecker, that animal would correspond to a project logo I have to use. Thanks for the tip with www.wallhaven.cc. Maybe I'll use one of [their woodpecker images](https://wallhaven.cc/search?q=woodpecker&categories=100&purity=100&topRange=1y&sorting=toplist&order=desc) .

**Comment by felipecrs** [comment]
I think I'll revert to the default Ubuntu wallpaper until I find a better one. The main focus is that it needs to be neutral.

**Comment by knbknb** [comment]
You could just use a blank color then? 

In the new theme/design, I like how how the user sees first a blurred wallpaper at the login screen that looks mysterious and slightly badass (just as the current cityscape does, in blurred state), but then the cityscape is kind of banal , or too obvious (at least to me)

I have written/adapted a little shellscript that will change the background to that woodpecker, though.
