### ISSUE TITLE
Gnome  Dock Position cannot be changed by logged-in user, and dock does not auto-hide

### ISSUE THREAD

**Issue by knbknb** [felipecrs/dev-ubuntu#31]
Perhaps it's just me but I cannot change the dock position of the theme. And I cannot change any other setting such as "auto-hide the dock". Currently the dock is always visible.

In the Gnome Settings App, Menu "Dock" there are some settings available for customization, but changing them has no effect.

**Comment by knbknb** [comment]
I have figured it out.- I have to disable the "Dash To Panel" Setting in the "Tweaks" Application.

**Comment by felipecrs** [comment]
The **Dock** option on **Settings** app points to the **Ubuntu Dock**, which is disabled in this VM. 

You have to configure in **Dash to Panel** instead, as you already stated.

![image](https://user-images.githubusercontent.com/29582865/76230130-03b6f500-6202-11ea-9469-9513495535c8.png)
